# Generated by Django 5.2.9 on 2025-12-17 20:05

import media.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('_internal_id', models.CharField(blank=True, max_length=50)),
                ('duration', models.IntegerField()),
                ('narrator', models.CharField(max_length=100)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrowed_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(media.mixins.DownloadableMixin, media.mixins.BorrowableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('_internal_id', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(max_length=20)),
                ('page_count', models.IntegerField()),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrowed_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(media.mixins.BorrowableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('_internal_id', models.CharField(blank=True, max_length=50)),
                ('duration', models.IntegerField(help_text='Длительность в минутах')),
                ('format', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(media.mixins.DownloadableMixin, models.Model),
        ),
    ]
