# Generated by Django 5.2.9 on 2025-12-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Не указан', max_length=50),
        ),
    ]
